services:
  db:
    image: mongo:latest
    container_name: mern_mongo_db
    restart: unless-stopped
    environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
